/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const InvestigationStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'submitted' : IDL.Null,
  'underInvestigation' : IDL.Null,
  'inconclusive' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhenomenaType = IDL.Variant({
  'electromagneticAnomalies' : IDL.Null,
  'unexplainedSounds' : IDL.Null,
  'movingObjects' : IDL.Null,
  'apparitions' : IDL.Null,
});
export const ParanormalCase = IDL.Record({
  'status' : InvestigationStatus,
  'contactInfo' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'caseId' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
  'phenomenaType' : PhenomenaType,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'filterCasesByLocation' : IDL.Func([IDL.Text], [IDL.Vec(ParanormalCase)], []),
  'filterCasesByType' : IDL.Func(
      [PhenomenaType],
      [IDL.Vec(ParanormalCase)],
      [],
    ),
  'getAllCases' : IDL.Func([], [IDL.Vec(ParanormalCase)], []),
  'getCaseById' : IDL.Func([IDL.Text], [IDL.Opt(ParanormalCase)], []),
  'submitCase' : IDL.Func(
      [IDL.Text, PhenomenaType, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'updateCaseStatus' : IDL.Func(
      [IDL.Text, InvestigationStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const InvestigationStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'submitted' : IDL.Null,
    'underInvestigation' : IDL.Null,
    'inconclusive' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhenomenaType = IDL.Variant({
    'electromagneticAnomalies' : IDL.Null,
    'unexplainedSounds' : IDL.Null,
    'movingObjects' : IDL.Null,
    'apparitions' : IDL.Null,
  });
  const ParanormalCase = IDL.Record({
    'status' : InvestigationStatus,
    'contactInfo' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'caseId' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
    'phenomenaType' : PhenomenaType,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'filterCasesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ParanormalCase)],
        [],
      ),
    'filterCasesByType' : IDL.Func(
        [PhenomenaType],
        [IDL.Vec(ParanormalCase)],
        [],
      ),
    'getAllCases' : IDL.Func([], [IDL.Vec(ParanormalCase)], []),
    'getCaseById' : IDL.Func([IDL.Text], [IDL.Opt(ParanormalCase)], []),
    'submitCase' : IDL.Func(
        [IDL.Text, PhenomenaType, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'updateCaseStatus' : IDL.Func(
        [IDL.Text, InvestigationStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };