/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminCredentials { 'pin' : string, 'email' : string }
export interface Case {
  'id' : string,
  'ownerEmail' : string,
  'resolved' : boolean,
  'contactInfo' : string,
  'description' : string,
  'timestamp' : Time,
  'photo' : [] | [ExternalBlob],
  'location' : string,
  'phenomenaType' : string,
}
export interface CaseLookupResult {
  'hasCase' : boolean,
  'caseSummaries' : Array<CaseSummary>,
}
export interface CaseSummary {
  'status' : string,
  'caseId' : string,
  'location' : string,
  'phenomenaType' : string,
}
export type ExternalBlob = Uint8Array;
export interface Investigation {
  'status' : string,
  'title' : string,
  'date' : Time,
  'description' : string,
  'location' : string,
}
export interface TeamMember { 'bio' : string, 'name' : string, 'role' : string }
export interface Testimonial {
  'date' : Time,
  'quote' : string,
  'author' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvestigation' : ActorMethod<[string, Investigation], undefined>,
  'createTeamMember' : ActorMethod<[string, TeamMember], undefined>,
  'createTestimonial' : ActorMethod<[string, Testimonial], undefined>,
  'deleteCase' : ActorMethod<[string], boolean>,
  'deleteInvestigation' : ActorMethod<[string], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'getAdminCredentials' : ActorMethod<[], AdminCredentials>,
  'getAllCases' : ActorMethod<[], Array<Case>>,
  'getAllInvestigationCases' : ActorMethod<[], Array<Investigation>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCasesForUser' : ActorMethod<[string], CaseLookupResult>,
  'getInvestigation' : ActorMethod<[string], [] | [Investigation]>,
  'getTeamMember' : ActorMethod<[string], [] | [TeamMember]>,
  'getTestimonial' : ActorMethod<[string], [] | [Testimonial]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markCaseResolved' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCase' : ActorMethod<
    [string, string, string, string, [] | [ExternalBlob], string],
    string
  >,
  'updateInvestigation' : ActorMethod<[string, Investigation], undefined>,
  'updateTeamMember' : ActorMethod<[string, TeamMember], undefined>,
  'updateTestimonial' : ActorMethod<[string, Testimonial], undefined>,
  'verifyAdmin' : ActorMethod<[], boolean>,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];