/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Investigation {
  'status' : string,
  'title' : string,
  'date' : Time,
  'description' : string,
  'location' : string,
}
export interface TeamMember { 'bio' : string, 'name' : string, 'role' : string }
export interface Testimonial {
  'date' : Time,
  'quote' : string,
  'author' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvestigation' : ActorMethod<[string, Investigation], undefined>,
  'createTeamMember' : ActorMethod<[string, TeamMember], undefined>,
  'createTestimonial' : ActorMethod<[string, Testimonial], undefined>,
  'deleteInvestigation' : ActorMethod<[string], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'getAggregatedAnalytics' : ActorMethod<
    [],
    {
      'submissions' : Array<[string, bigint]>,
      'pageVisits' : Array<[string, bigint]>,
    }
  >,
  'getAllInvestigations' : ActorMethod<[], Array<Investigation>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvestigation' : ActorMethod<[string], [] | [Investigation]>,
  'getTeamMember' : ActorMethod<[string], [] | [TeamMember]>,
  'getTestimonial' : ActorMethod<[string], [] | [Testimonial]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordFormSubmission' : ActorMethod<[string], undefined>,
  'recordPageVisit' : ActorMethod<[string], undefined>,
  'updateInvestigation' : ActorMethod<[string, Investigation], undefined>,
  'updateTeamMember' : ActorMethod<[string, TeamMember], undefined>,
  'updateTestimonial' : ActorMethod<[string, Testimonial], undefined>,
  'verifyAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];