/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Investigation = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'date' : Time,
  'quote' : IDL.Text,
  'author' : IDL.Text,
});
export const AdminCredentials = IDL.Record({
  'pin' : IDL.Text,
  'email' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Case = IDL.Record({
  'id' : IDL.Text,
  'ownerEmail' : IDL.Text,
  'resolved' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
  'phenomenaType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CaseStatusChange = IDL.Record({
  'changedBy' : IDL.Text,
  'toStatus' : IDL.Text,
  'fromStatus' : IDL.Text,
  'timestamp' : Time,
  'caseId' : IDL.Text,
});
export const CaseSummary = IDL.Record({
  'status' : IDL.Text,
  'caseId' : IDL.Text,
  'location' : IDL.Text,
  'phenomenaType' : IDL.Text,
});
export const CaseLookupResult = IDL.Record({
  'hasCase' : IDL.Bool,
  'caseSummaries' : IDL.Vec(CaseSummary),
});
export const AdminCaseResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvestigation' : IDL.Func([IDL.Text, Investigation], [], []),
  'createTeamMember' : IDL.Func([IDL.Text, TeamMember], [], []),
  'createTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
  'deleteCase' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteInvestigation' : IDL.Func([IDL.Text], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'getAdminCredentials' : IDL.Func([], [AdminCredentials], ['query']),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getAllInvestigationCases' : IDL.Func(
      [],
      [IDL.Vec(Investigation)],
      ['query'],
    ),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseById' : IDL.Func([IDL.Text], [IDL.Opt(Case)], ['query']),
  'getCaseStatusChanges' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CaseStatusChange)],
      ['query'],
    ),
  'getCasesForUser' : IDL.Func([IDL.Text], [CaseLookupResult], ['query']),
  'getInvestigation' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Investigation)],
      ['query'],
    ),
  'getTeamMember' : IDL.Func([IDL.Text], [IDL.Opt(TeamMember)], ['query']),
  'getTestimonial' : IDL.Func([IDL.Text], [IDL.Opt(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initAdmin' : IDL.Func([], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markCaseResolved' : IDL.Func([IDL.Text, IDL.Text], [AdminCaseResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateInvestigation' : IDL.Func([IDL.Text, Investigation], [], []),
  'updateTeamMember' : IDL.Func([IDL.Text, TeamMember], [], []),
  'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
  'verifyAdmin' : IDL.Func([], [IDL.Bool], []),
  'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Investigation = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'date' : Time,
    'quote' : IDL.Text,
    'author' : IDL.Text,
  });
  const AdminCredentials = IDL.Record({ 'pin' : IDL.Text, 'email' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Case = IDL.Record({
    'id' : IDL.Text,
    'ownerEmail' : IDL.Text,
    'resolved' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
    'phenomenaType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CaseStatusChange = IDL.Record({
    'changedBy' : IDL.Text,
    'toStatus' : IDL.Text,
    'fromStatus' : IDL.Text,
    'timestamp' : Time,
    'caseId' : IDL.Text,
  });
  const CaseSummary = IDL.Record({
    'status' : IDL.Text,
    'caseId' : IDL.Text,
    'location' : IDL.Text,
    'phenomenaType' : IDL.Text,
  });
  const CaseLookupResult = IDL.Record({
    'hasCase' : IDL.Bool,
    'caseSummaries' : IDL.Vec(CaseSummary),
  });
  const AdminCaseResult = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvestigation' : IDL.Func([IDL.Text, Investigation], [], []),
    'createTeamMember' : IDL.Func([IDL.Text, TeamMember], [], []),
    'createTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
    'deleteCase' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteInvestigation' : IDL.Func([IDL.Text], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'getAdminCredentials' : IDL.Func([], [AdminCredentials], ['query']),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getAllInvestigationCases' : IDL.Func(
        [],
        [IDL.Vec(Investigation)],
        ['query'],
      ),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseById' : IDL.Func([IDL.Text], [IDL.Opt(Case)], ['query']),
    'getCaseStatusChanges' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CaseStatusChange)],
        ['query'],
      ),
    'getCasesForUser' : IDL.Func([IDL.Text], [CaseLookupResult], ['query']),
    'getInvestigation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Investigation)],
        ['query'],
      ),
    'getTeamMember' : IDL.Func([IDL.Text], [IDL.Opt(TeamMember)], ['query']),
    'getTestimonial' : IDL.Func([IDL.Text], [IDL.Opt(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initAdmin' : IDL.Func([], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markCaseResolved' : IDL.Func([IDL.Text, IDL.Text], [AdminCaseResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'updateInvestigation' : IDL.Func([IDL.Text, Investigation], [], []),
    'updateTeamMember' : IDL.Func([IDL.Text, TeamMember], [], []),
    'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
    'verifyAdmin' : IDL.Func([], [IDL.Bool], []),
    'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };